### ISSUE TITLE
Arc of Arc

### ISSUE THREAD

**Issue by davidrjonas** [kardeiz/jsonrpc-v2#1]
I was looking through your code after your recent reddit post and I noticed this line.

https://github.com/kardeiz/jsonrpc-v2/blob/master/src/lib.rs#L866

Should that be `let cloned = Arc::clone(self);` since self is `Arc<Self>`? I didn't test it or anything, just thought I'd point it out.

**Comment by kardeiz** [comment]
Good catch, thanks! The signature was initially `into_actix_web_service(self)`, but then I realized it would be necessary to wrap the server in an `Arc` before the call to `into_actix_web_service` (in order to move the server into the `actix_web::HttpServer::new` block). I then forgot to update this line. 

I've fixed this in a new release [`0.4.1`](https://crates.io/crates/jsonrpc-v2/0.4.1), so closing this now. Thanks again!
